const { withPodfile } = require("expo/config-plugins");

/**
 * RCTThirdPartyComponentsProvider.mm (generated by RN codegen) creates an
 * NSDictionary literal using NSClassFromString(). With old architecture,
 * Fabric component classes don't exist, so NSClassFromString returns nil.
 * Inserting nil into @{} crashes: "attempt to insert nil object from objects[0]".
 *
 * This plugin adds a post_install hook that rewrites the file to use
 * NSMutableDictionary with nil guards.
 */
module.exports = function withNilSafeFabricProvider(config) {
  return withPodfile(config, (config) => {
    const patchScript = `
    # Patch RCTThirdPartyComponentsProvider to be nil-safe for old architecture
    provider_path = File.join(__dir__, 'build', 'generated', 'ios', 'RCTThirdPartyComponentsProvider.mm')
    if File.exist?(provider_path)
      content = File.read(provider_path)
      if content.include?('NSClassFromString') && content.include?('thirdPartyComponents = @{')
        content.gsub!(/thirdPartyComponents = @\\{([^}]+)\\};/m) do |match|
          pairs = Regexp.last_match(1).scan(/@"(\\w+)":\\s*NSClassFromString\\(@"(\\w+)"\\)/)
          lines = ["NSMutableDictionary *dict = [NSMutableDictionary new];"]
          pairs.each do |key, cls|
            lines << "    { Class c = NSClassFromString(@\\"#{cls}\\"); if (c) dict[@\\"#{key}\\"] = c; }"
          end
          lines << "    thirdPartyComponents = [dict copy];"
          lines.join("\\n")
        end
        File.write(provider_path, content)
      end
    end`;

    config.modResults.contents = config.modResults.contents.replace(
      /post_install do \|installer\|/,
      `post_install do |installer|${patchScript}`
    );

    return config;
  });
};
